//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.26 at 07:12:22 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8041/DBConnector/rest/tradpartners", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deva.webproj.jaxb;
