//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.26 at 07:12:22 PM IST 
//


package com.deva.webproj.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for partners complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="partners">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partnershipid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="owneruser" type="{http://localhost:8041/DBConnector/rest/tradpartners}UserProfileDetails"/>
 *         &lt;element name="partneruser" type="{http://localhost:8041/DBConnector/rest/tradpartners}UserProfileDetails"/>
 *         &lt;element name="charges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "partners", propOrder = {
    "partnershipid",
    "owneruser",
    "partneruser",
    "charges",
    "created"
})
public class Partners {

    protected int partnershipid;
    @XmlElement(required = true)
    protected UserProfileDetails owneruser;
    @XmlElement(required = true)
    protected UserProfileDetails partneruser;
    protected String charges;
    protected String created;

    /**
     * Gets the value of the partnershipid property.
     * 
     */
    public int getPartnershipid() {
        return partnershipid;
    }

    /**
     * Sets the value of the partnershipid property.
     * 
     */
    public void setPartnershipid(int value) {
        this.partnershipid = value;
    }

    /**
     * Gets the value of the owneruser property.
     * 
     * @return
     *     possible object is
     *     {@link UserProfileDetails }
     *     
     */
    public UserProfileDetails getOwneruser() {
        return owneruser;
    }

    /**
     * Sets the value of the owneruser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProfileDetails }
     *     
     */
    public void setOwneruser(UserProfileDetails value) {
        this.owneruser = value;
    }

    /**
     * Gets the value of the partneruser property.
     * 
     * @return
     *     possible object is
     *     {@link UserProfileDetails }
     *     
     */
    public UserProfileDetails getPartneruser() {
        return partneruser;
    }

    /**
     * Sets the value of the partneruser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProfileDetails }
     *     
     */
    public void setPartneruser(UserProfileDetails value) {
        this.partneruser = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharges(String value) {
        this.charges = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreated(String value) {
        this.created = value;
    }

}
