//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 12:05:48 AM IST 
//


package com.deva.webproj.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userprofile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userprofile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="compname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="compid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retention" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="userCreds" type="{http://localhost:8041/DBConnector/rest/user/profile}usercredentials" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userprofile", propOrder = {
    "compname",
    "compid",
    "address",
    "retention",
    "userCreds"
})
public class Userprofile {

    protected String compname;
    protected String compid;
    protected String address;
    protected Integer retention;
    protected Usercredentials userCreds;

    /**
     * Gets the value of the compname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompname() {
        return compname;
    }

    /**
     * Sets the value of the compname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompname(String value) {
        this.compname = value;
    }

    /**
     * Gets the value of the compid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompid() {
        return compid;
    }

    /**
     * Sets the value of the compid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompid(String value) {
        this.compid = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the retention property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRetention() {
        return retention;
    }

    /**
     * Sets the value of the retention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRetention(Integer value) {
        this.retention = value;
    }

    /**
     * Gets the value of the userCreds property.
     * 
     * @return
     *     possible object is
     *     {@link userCreds }
     *     
     */
    public Usercredentials getuserCreds() {
        return userCreds;
    }

    /**
     * Sets the value of the userCreds property.
     * 
     * @param value
     *     allowed object is
     *     {@link userCreds }
     *     
     */
    public void setuserCreds(Usercredentials value) {
        this.userCreds = value;
    }

}
